# docker-compose.prod.yml
services:
  # === API Gateway ===
  api-gateway:
    image: ghcr.io/${GHCR_OWNER:-lem0n4ell0}/api-gateway:${TAG:-latest}
    build: null  # отключаем сборку в проде
    restart: unless-stopped
    networks:
      - internal

  # === Auth Service ===
  authentication-service:
    image: ghcr.io/${GHCR_OWNER:-lem0n4ell0}/authentication-service:${TAG:-latest}
    build: null
    restart: unless-stopped
    networks:
      - internal

  # === SMTP Service ===
  notification-service:
    image: ghcr.io/${GHCR_OWNER:-lem0n4ell0}/notification-service:${TAG:-latest}
    build: null
    restart: unless-stopped
    networks:
      - internal

  # === Homeowners Service ===
  homeowners-service:
    image: ghcr.io/${GHCR_OWNER:-lem0n4ell0}/homeowners-service:${TAG:-latest}
    build: null
    restart: unless-stopped
    networks:
      - internal

  # === pgAdmin (без проброса порта — доступ через Nginx) ===
  pgadmin:
    ports: [ ]
    restart: unless-stopped
    networks:
      - internal

  # === Kafka UI (без проброса порта — доступ через Nginx) ===
  kafka-ui:
    ports: [ ]
    restart: unless-stopped
    networks:
      - internal

  frontend:
    image: ghcr.io/${GHCR_OWNER:-lem0n4ell0}/frontend:${TAG:-latest}
    ports:
      - "3000:80"
    networks:
      - internal
    restart: always