package ru.zeker.common.exception;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,
    MISSING_PARAMETER,
    INVALID_INPUT,
    TOKEN_EXPIRED,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_NOT_FOUND,
    EMAIL_TOKEN_EXPIRED,
    INVALID_EMAIL_TOKEN,
    AUTHORIZATION_ERROR,
    ACCESS_DENIED,
    BAD_CREDENTIALS,
    ACCOUNT_BLOCKED,
    ACCOUNT_DISABLED,
    TOO_MANY_RESEND_VERIFICATION,
    TOO_MANY_CODE_ATTEMPTS,
    USER_ALREADY_ACTIVATION,
    USER_NOT_FOUND,
    USER_EMAIL_ALREADY_USED,
    PERSONAL_DATA_CONSENT_REQUIRED
}
